from yaki.imports import *
from yaki.widgets import *
from yaki.app.common import *

# メイン画面
def set_frame1(page_x):
    global frame1,button45,buttonY,button143,combobox_frame,button_function_list,dist_button
    frame1 = ttk.Frame(root)
    root.protocol("WM_DELETE_WINDOW", frame_delete)
    random.seed(None)
    buttonY=Button(root)
    execute()
    men=Menu(root)
    root.config(menu=men)
    men1=Menu(men,relief=GROOVE,tearoff=0)
    men2=Menu(men,relief=GROOVE,tearoff=0)
    men3=Menu(men,relief=GROOVE,tearoff=0)
    men.add_cascade(label='メニュー', menu=men1)
    men.add_cascade(label='テーマ変更', menu=men2)
    men.add_cascade(label='設定', menu=men3)
    men3.add_command(label='スタートアップ登録', command=startup_reg)
    men1.add_command(label='バージョン確認', command=lambda: messagebox.showinfo("バージョン",f"Yuki's Army knife ver{version}"))
    men1.add_command(label='ホームページ', command=home_page)
    men1.add_command(label='新規ver確認',command=check_new_ver)
    #men1.add_command(label='ミニモード',command=mini_win)
    men2.add_command(label='デフォルト', command=lambda:set_theme(0))
    men2.add_command(label='モダン', command=lambda:set_theme(1))
    men2.add_command(label='ダーク', command=lambda:set_theme(2))
    men2.add_command(label='デジタル', command=lambda:set_theme(3))
    men2.add_command(label='ナチュラル', command=lambda:set_theme(5))
    men2.add_command(label='システマチック', command=lambda:set_theme(6))
    men2.add_command(label='ケラミック', command=lambda:set_theme(7))
    men2.add_command(label='木材風イエロー', command=lambda:set_theme(8))
    men2.add_command(label='プラスチック', command=lambda:set_theme(9))
    #men2.add_command(label='ラディエント', command=lambda:set_theme(10))
    men2.add_command(label='XP風', command=lambda:set_theme(11))
    men2.add_command(label='砂風', command=lambda:set_theme(12))
    men2.add_command(label='クラッシック', command=lambda:set_theme(13))
    men2.add_command(label='モダンダーク', command=lambda:set_theme(14))
    men2.add_command(label='モダンライト', command=lambda:set_theme(15))
    men3.add_command(label='タスクアイコンに登録', command=button_task_icon)
    men3.add_command(label='非表示にする機能を登録', command=del_func_set)
    men1.add_command(label='再起動', command=restart)
    men3.add_command(label='詳細設定', command=advanced_setting)
    men3.add_command(label='設定フォルダ', command=setting_folder)

    notebook = ttk.Notebook(frame1)
    frame_text=ttk.Frame(notebook,name="text")
    frame_video=ttk.Frame(notebook,name="video")
    frame_image=ttk.Frame(notebook,name="image")
    frame_other=ttk.Frame(notebook,name="other")
    frame_text1=ttk.Frame(frame_text,name="text1",relief=RIDGE,borderwidth=3,padding=7)
    frame_text2=ttk.Frame(frame_text,name="text2",relief=RIDGE,borderwidth=3,padding=7)
    frame_text3=ttk.Frame(frame_text,name="text3",relief=RIDGE,borderwidth=3,padding=7)
    frame_video1=ttk.Frame(frame_video,name="video1",relief=RIDGE,borderwidth=3,padding=7)
    frame_video2=ttk.Frame(frame_video,name="video2",relief=RIDGE,borderwidth=3,padding=7)
    frame_video3=ttk.Frame(frame_video,name="video3",relief=RIDGE,borderwidth=3,padding=7)
    frame_image1=ttk.Frame(frame_image,name="image1",relief=RIDGE,borderwidth=3,padding=7)
    frame_image2=ttk.Frame(frame_image,name="image2",relief=RIDGE,borderwidth=3,padding=7)
    frame_image3=ttk.Frame(frame_image,name="image3",relief=RIDGE,borderwidth=3,padding=7)
    frame_other1=ttk.Frame(frame_other,name="other1",relief=RIDGE,borderwidth=3,padding=7)
    frame_other2=ttk.Frame(frame_other,name="other2",relief=RIDGE,borderwidth=3,padding=7)
    frame_other3=ttk.Frame(frame_other,name="other3",relief=RIDGE,borderwidth=3,padding=7)
    frame_config=ttk.Frame(frame1)
    notebook.add(frame_text, text="テキスト・情報")
    notebook.add(frame_video, text="動画・音声")
    notebook.add(frame_image, text="画像・PDF")
    notebook.add(frame_other, text="システム・小物")
    buttonX=ttk.Checkbutton(
        frame_config,
        text=main_checkbox_name,
        onvalue=1,
        offvalue=0,
        variable=window_front,
        command=execute
        )
    #buttonZ=Button(
    #    frame_config,
    #    text="ミニモード",
    #    command=mini_win,
    #    bg="gray",
    #    fg="white"
    #)
    button1 = ttk.Button(
        frame_text2,
        width=13,
        text='文字カウント',
        command=count
    )
    button2 = ttk.Button(
        frame_text1,
        width=13,
        text='空白削除',
        command=blank
    )
    button3 = ttk.Button(
        frame_text1,
        width=13,
        text='置換',
        command=tikan
    )
    button4=ttk.Button(
        frame_text2,
        width=13,
        text="ネット検索",
        command=serch
    )
    button5=ttk.Button(
        frame_text1,
        width=13,
        text="抽選",
        command=choose
    )
    button6=ttk.Button(
        frame_other1,
        width=13,
        text="IPアドレス",
        command=IP
    )
    button7=ttk.Button(
        frame_other3,
        width=13,
        text="タイマー",
        command=timer
    )
    button8=ttk.Button(
        frame_other2,
        width=13,
        text="フォルダ作成",
        command=folder
    )
    button9=ttk.Button(
        frame_other2,
        width=13,
        text="パス取得",
        command=local_pass
    )
    button10=ttk.Button(
        frame_other3,
        width=13,
        text="カウンター",
        command=count_down
    )
    button11=ttk.Button(
        frame_video3,
        width=13,
        text="動画DL",
        command=video_dwonload
    )
    button12=ttk.Button(
        frame_image2,
        width=13,
        text="画像リサイズ",
        command=image_resize
    )
    button13=ttk.Button(
        frame_image3,
        width=13,
        text="画像変換",
        command=image_change
    )
    button14=ttk.Button(
        frame_image3,
        width=13,
        text="QR作成",
        command=qr_generate
    )
    button15=ttk.Button(
        frame_image3,
        width=13,
        text="QR読み取り",
        command=qr_reader
    )
    button16=ttk.Button(
        frame_image2,
        width=13,
        text="自動顔モザイク",
        command=face_mosaic
    )
    button17=ttk.Button(
        frame_image2,
        width=13,
        text="画像を回転",
        command=img_rotate
    )
    button18=ttk.Button(
        frame_image2,
        width=13,
        text="グレースケール",
        command=img_gray
    )
    button19=ttk.Button(
        frame_video1,
        width=13,
        text="動画カット",
        command=video_cut
    )
    button20=ttk.Button(
        frame_image2,
        width=13,
        text="トリミング",
        command=img_triming
    )
    button21=ttk.Button(
        frame_image3,
        width=13,
        text="画像圧縮",
        command=img_press
    )
    button22=ttk.Button(
        frame_other3,
        width=13,
        text="自動クリック",
        command=mouse_click
    )
    button23=ttk.Button(
        frame_video2,
        width=13,
        text="動画→音声",
        command=video_to_voice
    )
    button24=ttk.Button(
        frame_image1,
        width=13,
        text="PDF分解・抽出",
        command=pdf_split
    )
    button25=ttk.Button(
        frame_image1,
        width=13,
        text="PDF結合",
        command=pdf_merge
    )
    button26=ttk.Button(
        frame_other3,
        width=13,
        text="赤シート",
        command=red_sheet
    )
    button27=ttk.Button(
        frame_other1,
        width=13,
        text="スピードテスト",
        command=speed_check
    )
    button28=ttk.Button(
        frame_image3,
        width=13,
        text="EXIF",
        command=exif
    )
    button29=ttk.Button(
        frame_other3,
        width=13,
        text="付箋作成",
        command=memo
    )
    button30=ttk.Button(
        frame_video2,
        width=13,
        text="動画→GIF",
        command=video_to_gif
    )
    button31=ttk.Button(
        frame_image3,
        width=13,
        text="SVG変換",
        command=svg_con
    )
    button32=ttk.Button(
        frame_image3,
        width=13,
        text="透過PNG作成",
        command=img_inv
    )
    button33=ttk.Button(
        frame_other1,
        width=13,
        text="窓を最前面",
        command=front_window
    )
    button34=ttk.Button(
        frame_other3,
        width=13,
        text="画像付箋",
        command=screen_memo
    )
    button35=ttk.Button(
        frame_text3,
        width=13,
        text="短縮URL",
        command=short_url
    )
    button36=ttk.Button(
        frame_other1,
        width=13,
        text="窓のexe取得",
        command=window_path
    )
    button37=ttk.Button(
        frame_image3,
        width=13,
        text="アイコン抽出",
        command=icon_image
    )
    button38=ttk.Button(
        frame_other1,
        width=13,
        text="スリープ防止",
        command=sleep_stop
        )
    button39=ttk.Button(
        frame_text2,
        width=13,
        text="テキスト取得",
        command=txt_get
    )
    button40=ttk.Button(
        frame_video1,
        width=13,
        text="音声カット",
        command=voice_cut
    )
    button41=ttk.Button(
        frame_text3,
        width=13,
        text="ダミー人間",
        command=dumy_human
    )
    button42=ttk.Button(
        frame_other3,
        width=13,
        text="簡易時計",
        command=clock
    )
    button43=ttk.Button(
        frame_text3,
        width=13,
        text="進数変換",
        command=num_change
    )
    button44=ttk.Button(
        frame_text2,
        width=13,
        text="合体ペースト",
        command=sum_paste
    )
    button45=ttk.Button(
        frame_text2,
        width=13,
        text="連続コピペ",
        command=copy_paste
    )
    button46=ttk.Button(
        frame_other1,
        width=13,
        text="長さ測定",
        command=length_ruler
    )
    button47=ttk.Button(
        frame_video3,
        width=13,
        text="文章読み上げ",
        command=voice_read
    )
    button48=ttk.Button(
        frame_text3,
        width=13,
        text="パスワード生成",
        command=password
    )
    button49=ttk.Button(
        frame_other3,
        width=13,
        text="カラーパレット",
        command=color_bullet
    )
    button50=ttk.Button(
        frame_other2,
        width=13,
        text="更新日時編集",
        command=file_day
    )
    button51=ttk.Button(
        frame_video2,
        width=13,
        text="mp3↔wav",
        command=mp3_wav
    )
    button52=ttk.Button(
        frame_other1,
        width=13,
        text="システム使用率",
        command=pc_info
    )
    button53=ttk.Button(
        frame_video3,
        width=13,
        text="GIF作成",
        command=gif_create
    )
    button54=ttk.Button(
        frame_image2,
        width=13,
        text="画像余白追加",
        command=img_blank
    )
    button55=ttk.Button(
        frame_image2,
        width=13,
        text="画像調整",
        command=image_set
    )
    button56=ttk.Button(
        frame_image2,
        width=13,
        text="ガンマ補正",
        command=img_gamma
    )
    button57=ttk.Button(
        frame_image2,
        width=13,
        text="モザイク画像",
        command=area_mozaic
    )
    button58=ttk.Button(
        frame_text1,
        width=13,
        text="文字変換",
        command=translate
    )
    button59=ttk.Button(
        frame_video1,
        width=13,
        text="音量変更",
        command=video_volume
    )
    button60=ttk.Button(
        frame_video1,
        width=13,
        text="速度変更",
        command=video_speed
    )
    button61=ttk.Button(
        frame_video3,
        width=13,
        text="動画スクショ",
        command=video_shot
    )
    button62=ttk.Button(
        frame_video3,
        width=13,
        text="動画情報",
        command=video_info
    )
    button63=ttk.Button(
        frame_text3,
        width=13,
        text="md→html",
        command=md2html
    )
    button64=ttk.Button(
        frame_video1,
        width=13,
        text="動画結合",
        command=video_concat
    )
    button65=ttk.Button(
        frame_video2,
        width=13,
        text="音声→動画",
        command=voice2video
    )
    button66=ttk.Button(
        frame_other2,
        width=13,
        text="zip作成",
        command=compress
    )
    button67=ttk.Button(
        frame_other2,
        width=13,
        text="zip解凍",
        command=decompress
    )
    button68=ttk.Button(
        frame_image3,
        width=13,
        text="画像情報",
        command=image_info
    )
    button69=ttk.Button(
        frame_other1,
        width=13,
        text="窓透明化",
        command=window_toumei
    )
    button70=ttk.Button(
        frame_text3,
        width=13,
        text="URL変換",
        command=url_change
    )
    button71=ttk.Button(
        frame_video3,
        width=13,
        text="文字起こし",
        command=voice2read
    )
    button72=ttk.Button(
        frame_video1,
        width=13,
        text="動画リサイズ",
        command=video_size
    )
    button73=ttk.Button(
        frame_video1,
        width=13,
        text="動画白黒化",
        command=video_BW
    )
    button74=ttk.Button(
        frame_video1,
        width=13,
        text="動画色調整",
        command=video_light
    )
    button75=ttk.Button(
        frame_video1,
        width=13,
        text="動画余白",
        command=video_frame
    )
    #button76=ttk.Button(
    #    frame_text3,
    #    width=13,
    #    text="色コード変換",
    #    command=color_code
    #)
    button76=ttk.Button(
        frame_other3,
        width=13,
        text="マスコット化",
        command=desc_mascot
    )
    button77=ttk.Button(
        frame_text3,
        width=13,
        text="翻訳",
        command=translate_text
    )
    button78=ttk.Button(
        frame_text2,
        width=13,
        text="パスワード確認",
        command=pass_check
    )
    button79=ttk.Button(
        frame_video2,
        width=13,
        text="動画→映像",
        command=voice_delete
    )
    button80=ttk.Button(
        frame_text3,
        width=13,
        text="サイトタイトル",
        command=site_title
    )
    button81=ttk.Button(
        frame_other1,
        width=13,
        text="通信監視",
        command=network_monitor
        )
    button82=ttk.Button(
        frame_text1,
        width=13,
        text="改行調整",
        command=n_del
    )
    button83=ttk.Button(
        frame_image2,
        width=13,
        text="画像反転",
        command=image_mirror
    )
    button84=ttk.Button(
        frame_video1,
        width=13,
        text="動画反転",
        command=video_mirror
    )
    button85=ttk.Button(
        frame_text1,
        width=13,
        text="プレーン貼付",
        command=plain_paste
    )
    button86=ttk.Button(
        frame_other1,
        width=13,
        text="電源操作",
        command=power_control
    )
    button87=ttk.Button(
        frame_text1,
        width=13,
        text="ソート",
        command=sort_list
    )
    button89=ttk.Button(
        frame_image1,
        width=13,
        text="PDFパス解除",
        command=pdf_pass
    )
    button88=ttk.Button(
        frame_other3,
        width=13,
        text="BMI計算",
        command=bmi
    )
    button90=ttk.Button(
        frame_other1,
        width=13,
        text="通信先表示",
        command=net_info
    )
    button91=ttk.Button(
        frame_video3,
        width=13,
        text="GIF分解",
        command=gif_split
    )
    button92=ttk.Button(
        frame_image2,
        width=13,
        text="台形補正",
        command=trapezoid
    )
    button93=ttk.Button(
        frame_image2,
        width=13,
        text="書類影削除",
        command=shadow_delete
    )
    button94=ttk.Button(
        frame_video2,
        width=13,
        text="動画変換",
        command=video_convert
    )
    button95=ttk.Button(
        frame_video1,
        width=13,
        text="FPS変更",
        command=video_fps
    )
    button96=ttk.Button(
        frame_video1,
        width=13,
        text="動画音声変更",
        command=video_bgm
    )
    button97=ttk.Button(
        frame_text1,
        width=13,
        text="重複削除",
        command=duplication
    )
    button98=ttk.Button(
        frame_video3,
        width=13,
        text="サムネ取得",
        command=video_thumbnail
    )
    button99=ttk.Button(
        frame_text3,
        width=13,
        text="住所英語化",
        command=address_english
    )
    button100=ttk.Button(
        frame_other1,
        width=13,
        text="入力一時停止",
        command=input_stop
    )
    button101=ttk.Button(
        frame_text1,
        width=13,
        text="連番リスト",
        command=renban_list
    )
    button102=ttk.Button(
        frame_video3,
        width=13,
        text="WEBカメラ",
        command=web_camera
    )
    button103=ttk.Button(
        frame_video1,
        width=13,
        text="動画フェード",
        command=vidwo_fade
    )
    button104=ttk.Button(
        frame_other2,
        width=13,
        text="ファイル暗号化",
        command=aes_file
    )
    button105=ttk.Button(
        frame_video3,
        width=13,
        text="動画字幕DL",
        command=video_str
    )
    button106=ttk.Button(
        frame_other2,
        width=13,
        text="完全削除",
        command=delete2file
    )
    button107=ttk.Button(
        frame_other1,
        width=13,
        text="窓中心配置",
        command=window_center
    )
    button108=ttk.Button(
        frame_image3,
        width=13,
        text="画像結合",
        command=image_join
    )
    button109=ttk.Button(
        frame_image3,
        width=13,
        text="コピー画像取得",
        command=get_copyimage
    )
    button110=ttk.Button(
        frame_text2,
        width=13,
        text="テキスト検索",
        command=text_search
    )
    button111=ttk.Button(
        frame_image3,
        width=13,
        text="サイト画像DL",
        command=site_image
    )
    button112=ttk.Button(
        frame_other3,
        width=13,
        text="ダイス",
        command=dice
    )
    button113=ttk.Button(
        frame_text3,
        width=13,
        text="ダミー文章",
        command=dummy_txt
    )
    button114=ttk.Button(
        frame_image3,
        width=13,
        text="ダミー画像",
        command=dummy_img
    )
    button115=ttk.Button(
        frame_text3,
        width=13,
        text="UNIXタイム",
        command=unix_time
    )
    button116=ttk.Button(
        frame_video3,
        width=13,
        text="web動画情報",
        command=web_video_info
    )
    button117=ttk.Button(
        frame_text1,
        width=13,
        text="空行削除",
        command=empty_line
    )
    button118=ttk.Button(
        frame_video1,
        width=13,
        text="MP3タグ編集",
        command=mp3_tag
    )
    button119=ttk.Button(
        frame_image1,
        width=13,
        text="PDF文章抽出",
        command=pdf_text
    )
    button120=ttk.Button(
        frame_other2,
        width=13,
        text="ファイルハッシュ",
        command=file_hash
    )
    button121=ttk.Button(
        frame_text3,
        width=13,
        text="文字列ハッシュ",
        command=text_hash
    )
    button122=ttk.Button(
        frame_image3,
        width=13,
        text="画像→base64",
        command=image_base64
    )
    button123=ttk.Button(
        frame_text3,
        width=13,
        text="URLショトカ",
        command=url_shotcut
    )
    button124=ttk.Button(
        frame_other1,
        width=13,
        text="Explore再起動",
        command=explore_restart
    )
    button125=ttk.Button(
        frame_other1,
        width=13,
        text="神モード",
        command=godmode
    )
    button126=ttk.Button(
        frame_text1,
        width=13,
        text="筆記体変換",
        command=cursive
    )
    button127=ttk.Button(
        frame_other3,
        width=13,
        text="割り勘計算",
        command=warikan
    )
    button128=ttk.Button(
        frame_other3,
        width=13,
        text="カラーピッカー",
        command=color_picker
    )
    button129=ttk.Button(
        frame_other3,
        width=13,
        text="拡大鏡",
        command=magnifier
    )
    button130=ttk.Button(
        frame_text3,
        width=13,
        text="Excel↔CSV",
        command=excel_csv
    )
    button131=ttk.Button(
        frame_text3,
        width=13,
        text="JSON↔CSV",
        command=json_csv
    )
    button132=ttk.Button(
        frame_text1,
        width=13,
        text="UTF正規化",
        command=unicode_normalize
    )
    button133=ttk.Button(
        frame_image3,
        width=13,
        text="office画像抽出",
        command=office_image
    )
    button134=ttk.Button(
        frame_video3,
        width=13,
        text="GIF撮影",
        command=gif_video
    )
    button135=ttk.Button(
        frame_video3,
        width=13,
        text="メトローム",
        command=metrome
    )
    button136=ttk.Button(
        frame_text3,
        width=13,
        text="OGP取得",
        command=ogp
    )
    button137=ttk.Button(
        frame_image3,
        width=13,
        text="画像直接コピー",
        command=copy_image
    )
    button138=ttk.Button(
        frame_text3,
        width=13,
        text="クラウドDL",
        command=cloud_download
    )
    button139=ttk.Button(
        frame_video1,
        width=13,
        text="音声結合",
        command=voice_concat
    )
    button140=ttk.Button(
        frame_text3,
        width=13,
        text="JSON整形",
        command=json_format
    )
    button141=ttk.Button(
        frame_other1,
        width=13,
        text="環境変数",
        command=env_word
    )
    button142=ttk.Button(
        frame_text3,
        width=13,
        text="西暦↔和暦",
        command=seiwa
    )
    button143=ttk.Button(
        frame_other1,
        width=13,
        text="壁紙スラショ",
        command=wallpaper
    )
    button144=ttk.Button(
        frame_image1,
        width=13,
        text="PDF画像抽出",
        command=pdf_image
    )
    button145=ttk.Button(
        frame_image1,
        width=13,
        text="PDF圧縮",
        command=pdf_press
    )
    button146=ttk.Button(
        frame_image1,
        width=13,
        text="PDF回転",
        command=pdf_rotate
    )
    button147=ttk.Button(
        frame_other1,
        width=13,
        text="窓強制終了",
        command=window_kill
    )
    button148=ttk.Button(
        frame_other3,
        width=13,
        text="日数計算",
        command=time_calc
    )
    button149=ttk.Button(
        frame_other3,
        width=13,
        text="黄金比計算",
        command=golden_ratio
    )
    button150=ttk.Button(
        frame_video3,
        width=13,
        text="電子音ピアノ",
        command=piano
    )
    button151=ttk.Button(
        frame_other3,
        width=13,
        text="為替変換",
        command=exchange
    )
    button152=ttk.Button(
        frame_other3,
        width=13,
        text="得点計算",
        command=score_calc
    )
    button153=ttk.Button(
        frame_video3,
        width=13,
        text="動画経過画像",
        command=video_time_image
    )
    button154=ttk.Button(
        frame_image1,
        width=13,
        text="PDF挿入",
        command=pdf_insert
    )
    button155=ttk.Button(
        frame_other3,
        width=13,
        text="単語帳",
        command=word_book
    )
    button156=ttk.Button(
        frame_text3,
        width=13,
        text="カラー情報",
        command=color_name
    )
    button157=ttk.Button(
        frame_other3,
        width=13,
        text="自動操作",
        command=auto_oparation
    )
    button158=ttk.Button(
        frame_text2,
        width=13,
        text="強制ペースト",
        command=compulsion_paste
    )
    button159=ttk.Button(
        frame_other3,
        width=13,
        text="窓をトレイ",
        command=window_tray
    )
    button160=ttk.Button(
        frame_text3,
        width=13,
        text="文字コード変更",
        command=code_change
    )
    button161=ttk.Button(
        frame_text2,
        width=13,
        text="文字コード判別",
        command=code_check
    )
    button162=ttk.Button(
        frame_other3,
        width=13,
        text="マウス強調",
        command=mouse_highlight
    )
    button163=ttk.Button(
        frame_image3,
        width=13,
        text="画像→Excel",
        command=image_excel
    )
    button164=ttk.Button(
        frame_text2,
        width=13,
        text="MD編集",
        command=markdown_edit
    )
    button165=ttk.Button(
        frame_image3,
        width=13,
        text="HEIC変換",
        command=heic_convert
    )
    button166=ttk.Button(
        frame_other3,
        width=13,
        text="ワンタイムパス",
        command=totp_generator
    )
    button167=ttk.Button(
        frame_video1,
        width=13,
        text="等間隔分割",
        command=video_equally
    )
    button168=ttk.Button(
        frame_video1,
        width=13,
        text="動画音声分割",
        command=video_audio_split
    )
    button169=ttk.Button(
        frame_image3,
        text="数式画像",
        width=13,
        command=formula_image
    )
    button170=ttk.Button(
        frame_video1,
        width=13,
        text="動画回転",
        command=video_rotate
    )
    button171=ttk.Button(
        frame_video1,
        width=13,
        text="音量正規化",
        command=video_normalize
    )
    button172=ttk.Button(
        frame_video1,
        width=13,
        text="動画音声ループ",
        command=video_loop
    )
    button173=ttk.Button(
        frame_video1,
        width=13,
        text="動画色反転",
        command=video_invert
    )
    button174=ttk.Button(
        frame_video1,
        width=13,
        text="音声フェード",
        command=audio_fade
    )
    button175=ttk.Button(
        frame_text3,
        width=13,
        text="JSON↔YAML",
        command=json_yaml
    )
    button176=ttk.Button(
        frame_image3,
        width=13,
        text="重畳表示",
        command=image_superimposed
    )
    button177=ttk.Button(
        frame_image1,
        width=13,
        text="PDF全文検索",
        command=pdf_search
    )
    button178=ttk.Button(
        frame_video3,
        width=13,
        text="QRカメラ取得",
        command=qr_camera
    )
    button179=ttk.Button(
        frame_image3,
        width=13,
        text="文字画像生成",
        command=text_image
    )
    button180=ttk.Button(
        frame_text3,
        width=13,
        text="サムネmd化",
        command=thumbnail_md
    )
    button181=ttk.Button(
        frame_text2,
        width=13,
        text="定型文",
        command=text_template
    )
    button182=ttk.Button(
        frame_text3,
        width=13,
        text="命名規則",
        command=naming_rule
    )
    button183=ttk.Button(
        frame_text3,
        width=13,
        text="csv↔md表変換",
        command=csv_md
    )
    button184=ttk.Button(
        frame_text1,
        width=13,
        text="コピー書換",
        command=copy_replace
    )
    button185=ttk.Button(
        frame_other2,
        width=13,
        text="RSA暗号化",
        command=rsa_encrypt
    )
    button186=ttk.Button(
        frame_text3,
        width=13,
        text="テキストdiff",
        command=text_diff
    )
    button187=ttk.Button(
        frame_image2,
        width=13,
        text="画像丸切取",
        command=image_round
    )
    button188=ttk.Button(
        frame_other2,
        width=13,
        text="ファイル判別",
        command=file_type
    )
    button189=ttk.Button(
        frame_image3,
        width=13,
        text="WEBP圧縮",
        command=webp_compress
    )
    button190=ttk.Button(
        frame_other2,
        width=13,
        text="ファイル削除",
        command=file_delete
    )
    button191=ttk.Button(
        frame_other1,
        width=13,
        text="プロセス優先度",
        command=process_priority
    )
    button192=ttk.Button(
        frame_image3,
        width=13,
        text="コード画像化",
        command=code_image
    )
    button193=ttk.Button(
        frame_image3,
        width=13,
        text="画像比較",
        command=image_compare
    )
    button194=ttk.Button(
        frame_text3,
        width=13,
        text="webファイル圧縮",
        command=web_compress
    )
    button195=ttk.Button(
        frame_other2,
        width=13,
        text="パス付きzip作成",
        command=zip_pass
    )
    button196=ttk.Button(
        frame_text2,
        width=13,
        text="パスワード管理",
        command=password_manages
    )
    button197=ttk.Button(
        frame_image3,
        width=13,
        text="ico作成",
        command=ico_create
    )
    button198=ttk.Button(
        frame_text2,
        width=13,
        text="webブックマーク",
        command=web_bookmark
    )


    kinou=198

    label_text=Label(frame_text,text="テキスト・情報",bg="green",fg="white")
    label_image=Label(frame_image,text="画像・PDF",bg="#800000",fg="white")
    label_video=Label(frame_video,text="動画・音声",bg="blue",fg="white")
    label_other=Label(frame_other,text="ファイル・小物ツール",bg="purple",fg="white")
    label_text1=Label(frame_text1,text="テキスト編集",fg="green")
    label_text2=Label(frame_text2,text="その他",fg="green")
    label_text3=Label(frame_text3,text="情報変換・生成",fg="green")
    label_video1=Label(frame_video1,text="編集",fg="blue")
    label_video2=Label(frame_video2,text="変換",fg="blue")
    label_video3=Label(frame_video3,text="その他",fg="blue")
    label_image1=Label(frame_image2,text="画像編集",fg="#800000")
    label_image2=Label(frame_image3,text="画像その他",fg="#800000")
    label_image3=Label(frame_image1,text="PDF編集",fg="#800000")
    label_other1=Label(frame_other3,text="小物ツール",fg="purple")
    label_other2=Label(frame_other2,text="フォルダ・ファイル",fg="purple")
    label_other3=Label(frame_other1,text="システム",fg="purple")

    def on_combobox_key_release(event):
        current_text = combobox_var.get()
        # 部分一致検索
        filtered_list = [item for item in list_button if current_text.lower() in item.lower()]
        # リスト更新
        combobox_frame['values'] = filtered_list

    def combo_selected(event):
        name_button=combobox_frame.get()
        dist_button[name_button]()

    combobox_var = StringVar()
    combobox_frame = ttk.Combobox(frame_config, textvariable=combobox_var)

    frame1.pack()

    frame_config.pack(side=TOP)
    #s = ttk.Style(root)
    #s.configure("TNotebook", tabposition='n')
    notebook.pack(side=TOP,expand=True, fill='both')

    buttonX.grid(row=0,column=0)
    #buttonZ.grid(row=0,column=0)
    combobox_frame.grid(row=0,column=1,columnspan=2)

    #frame_text.pack(side=TOP)
    label_text.pack(side=TOP)
    frame_text1.pack(side=TOP)
    frame_text3.pack(side=TOP)
    frame_text2.pack(side=TOP)
    label_text1.grid(row=0,column=0)
    label_text3.grid(row=0,column=0)
    label_text2.grid(row=0,column=0)

    #frame_image.pack(side=TOP)
    label_image.pack(side=TOP)
    frame_image1.pack(side=TOP)
    frame_image2.pack(side=TOP)
    frame_image3.pack(side=TOP)
    label_image1.grid(row=0,column=0)
    label_image2.grid(row=0,column=0)
    label_image3.grid(row=0,column=0)

    #frame_video.pack(side=TOP)
    label_video.pack(side=TOP)
    frame_video1.pack(side=TOP)
    frame_video2.pack(side=TOP)
    frame_video3.pack(side=TOP)
    label_video1.grid(row=0,column=0)
    label_video2.grid(row=0,column=0)
    label_video3.grid(row=0,column=0)

    #frame_other.pack(side=TOP)
    label_other.pack(side=TOP)
    frame_other1.pack(side=TOP)
    frame_other2.pack(side=TOP)
    frame_other3.pack(side=TOP)
    label_other1.grid(row=0,column=0)
    label_other2.grid(row=0,column=0)
    label_other3.grid(row=0,column=0)

    notebook.select(page_x)
    combobox_frame.focus_set()

    def on_focus_in(event):
        if frame_config.winfo_exists():
            combobox_frame.focus_set()
    def handle_keypress(event):
        if event.keysym == 'Return':
            show_dropdown(event)
        elif event.keysym == 'Delete':
            combobox_frame.delete(0,END)
    def show_dropdown(event):
        combobox_frame.event_generate('<Down>')

    root.bind('<FocusIn>', on_focus_in)
    combobox_frame.bind('<KeyPress>', handle_keypress)

    dist_button={}
    list_button=[]
    frame_textN1=1
    frame_textN2=1
    frame_textN3=1
    frame_videoN1=1
    frame_videoN2=1
    frame_videoN3=1
    frame_otherN1=1
    frame_otherN2=1
    frame_otherN3=1
    frame_imageN1=1
    frame_imageN2=1
    frame_imageN3=1
    width_range=main_frame_width
    for d in range(1,kinou+1):

        if f"button{str(d)}" in globals():
            dist_button[globals()["button"+str(d)]["text"]]=globals()["button"+str(d)].invoke
            list_button.append(globals()["button"+str(d)]["text"])
            if str(d) in del_func:
                continue
            if check_frame(globals()["button"+str(d)])=="text1":
                globals()["button"+str(d)].grid(row=frame_textN1//width_range,column=frame_textN1%width_range)
                frame_textN1+=1
            elif check_frame(globals()["button"+str(d)])=="text3":
                globals()["button"+str(d)].grid(row=frame_textN3//width_range,column=frame_textN3%width_range)
                frame_textN3+=1
            elif check_frame(globals()["button"+str(d)])=="text2":
                globals()["button"+str(d)].grid(row=frame_textN2//width_range,column=frame_textN2%width_range)
                frame_textN2+=1
            elif check_frame(globals()["button"+str(d)])=="video1":
                globals()["button"+str(d)].grid(row=frame_videoN1//width_range,column=frame_videoN1%width_range)
                frame_videoN1+=1
            elif check_frame(globals()["button"+str(d)])=="video2":
                globals()["button"+str(d)].grid(row=frame_videoN2//width_range,column=frame_videoN2%width_range)
                frame_videoN2+=1
            elif check_frame(globals()["button"+str(d)])=="video3":
                globals()["button"+str(d)].grid(row=frame_videoN3//width_range,column=frame_videoN3%width_range)
                frame_videoN3+=1
            elif check_frame(globals()["button"+str(d)])=="image1":
                globals()["button"+str(d)].grid(row=frame_imageN1//width_range,column=frame_imageN1%width_range)
                frame_imageN1+=1
            elif check_frame(globals()["button"+str(d)])=="image2":
                globals()["button"+str(d)].grid(row=frame_imageN2//width_range,column=frame_imageN2%width_range)
                frame_imageN2+=1
            elif check_frame(globals()["button"+str(d)])=="image3":
                globals()["button"+str(d)].grid(row=frame_imageN3//width_range,column=frame_imageN3%width_range)
                frame_imageN3+=1
            elif check_frame(globals()["button"+str(d)])=="other1":
                globals()["button"+str(d)].grid(row=frame_otherN1//width_range,column=frame_otherN1%width_range)
                frame_otherN1+=1
            elif check_frame(globals()["button"+str(d)])=="other2":
                globals()["button"+str(d)].grid(row=frame_otherN2//width_range,column=frame_otherN2%width_range)
                frame_otherN2+=1
            elif check_frame(globals()["button"+str(d)])=="other3":
                globals()["button"+str(d)].grid(row=frame_otherN3//width_range,column=frame_otherN3%width_range)
                frame_otherN3+=1
        else:
            dist_button[locals()["button"+str(d)]["text"]]=locals()["button"+str(d)].invoke
            list_button.append(locals()["button"+str(d)]["text"])
            if str(d) in del_func:
                continue
            if check_frame(locals()["button"+str(d)])=="text1":
                locals()["button"+str(d)].grid(row=frame_textN1//width_range,column=frame_textN1%width_range)
                frame_textN1+=1
            elif check_frame(locals()["button"+str(d)])=="text3":
                locals()["button"+str(d)].grid(row=frame_textN3//width_range,column=frame_textN3%width_range)
                frame_textN3+=1
            elif check_frame(locals()["button"+str(d)])=="text2":
                locals()["button"+str(d)].grid(row=frame_textN2//width_range,column=frame_textN2%width_range)
                frame_textN2+=1
            elif check_frame(locals()["button"+str(d)])=="video1":
                locals()["button"+str(d)].grid(row=frame_videoN1//width_range,column=frame_videoN1%width_range)
                frame_videoN1+=1
            elif check_frame(locals()["button"+str(d)])=="video2":
                locals()["button"+str(d)].grid(row=frame_videoN2//width_range,column=frame_videoN2%width_range)
                frame_videoN2+=1
            elif check_frame(locals()["button"+str(d)])=="video3":
                locals()["button"+str(d)].grid(row=frame_videoN3//width_range,column=frame_videoN3%width_range)
                frame_videoN3+=1
            elif check_frame(locals()["button"+str(d)])=="image1":
                locals()["button"+str(d)].grid(row=frame_imageN1//width_range,column=frame_imageN1%width_range)
                frame_imageN1+=1
            elif check_frame(locals()["button"+str(d)])=="image2":
                locals()["button"+str(d)].grid(row=frame_imageN2//width_range,column=frame_imageN2%width_range)
                frame_imageN2+=1
            elif check_frame(locals()["button"+str(d)])=="image3":
                locals()["button"+str(d)].grid(row=frame_imageN3//width_range,column=frame_imageN3%width_range)
                frame_imageN3+=1
            elif check_frame(locals()["button"+str(d)])=="other1":
                locals()["button"+str(d)].grid(row=frame_otherN1//width_range,column=frame_otherN1%width_range)
                frame_otherN1+=1
            elif check_frame(locals()["button"+str(d)])=="other2":
                locals()["button"+str(d)].grid(row=frame_otherN2//width_range,column=frame_otherN2%width_range)
                frame_otherN2+=1
            elif check_frame(locals()["button"+str(d)])=="other3":
                locals()["button"+str(d)].grid(row=frame_otherN3//width_range,column=frame_otherN3%width_range)
                frame_otherN3+=1

    combobox_frame['values'] = list_button
    button_function_list=list_button.copy()
    combobox_frame.bind('<KeyRelease>', on_combobox_key_release)
    combobox_frame.bind("<<ComboboxSelected>>",combo_selected)

    def on_mouse_wheel(event):
        try:
            # タブインデックスを取得
            current_tab = notebook.index(notebook.select())
            # ホイールの方向に応じてタブを移動
            if event.delta > 0 or event.num == 3:  # ホイール上/左ボタン（Linux）
                notebook.select(current_tab - 1 if current_tab > 0 else 0)
            elif event.delta < 0 or event.num == 4:  # ホイール下/右ボタン（Linux）
                notebook.select(current_tab + 1 if current_tab < notebook.index("end") - 1 else notebook.index("end") - 1)
        except:
            pass

    combobox_frame.unbind("<MouseWheel>")
    root.bind("<MouseWheel>", on_mouse_wheel)

